export default {
  businessName: "business_name",
  businessAddress: "address",
  businessDocument: "documento",
  businessCity: "email",
  systemName: "system_name",
  clientName: "nombres",
  clientDocument: "cc_cliente",
  clientAddress: "direccion",
  clientCity: "direccion",
  clientPhone: "telefonos",
  transactionTime: "hora",
  transactionDate: "fecha",
  businessTypeDocument: "razon_social",
  businessPhone: "phone2",
  businessPBX: "phone",
  numberTransaction: "consecutivo",
  totalTransaction: "total",
  totalPayed: "total",
  totalCambio: "",
  totalItems: "",
  tableNumber: "puesto",
};
